### ISSUE TITLE
ı have a problem

### ISSUE THREAD

**Issue by godsmels** [LizardX2/BTCMiner#1]
how to start tool ?

**Comment by qizq1337** [comment]
ITS A VIRUS MEN

**Comment by LizardX2** [comment]
To begin with, have you installed python?

**Comment by godsmels** [comment]
I don't think it's a virus, they suggested it on the cracked io site,
and no i didn't use pyhton i'm trying now

**Comment by godsmels** [comment]
I am getting python file not found error

**Comment by LizardX2** [comment]
msg me on telegram

**Comment by believer789201** [comment]
I am getting this error please resolve 


Traceback (most recent call last):
  File "/data/data/com.termux/files/home/BTCMiner/btcminer.py", line 178, in <module>
    main()
  File "/data/data/com.termux/files/home/BTCMiner/btcminer.py", line 152, in main
    hdwallet.from_mnemonic(mnemonic=custom_mnemonic)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/hdwallet/hdwallet.py", line 204, in from_mnemonic
    raise ValueError("Invalid mnemonic words.")
