### ISSUE TITLE
bruteforce stops working 

### ISSUE THREAD

**Issue by lxch3** [LizardX2/BTCMiner#5]
Traceback (most recent call last):
  File "/Users/user/Desktop/btc/btcminer.py", line 178, in <module>
    main()
  File "/Users/user/Desktop/btc/btcminer.py", line 122, in main
    balance = get_info[api_get_data][api_get_balance]
TypeError: 'NoneType' object is not subscriptable

keep getting this error

**Comment by yamildev01** [comment]
the script is deprecated, u have to use another api and it will work
